### ISSUE TITLE
run

### ISSUE THREAD

**Issue by werruww** [Cornell-RelaxML/qtip#15]
how to run it?

**Comment by werruww** [comment]
erorr

from model.cache_utils import StaticCache

from lib.utils.unsafe_import import model_from_hf_path

**Comment by werruww** [comment]
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "relaxml/Llama-2-7b-QTIP-2Bit"

model = AutoModelForCausalLM.from_pretrained(
    model_name, 
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

prompt = "Give me a short introduction to large language model."
messages = [
    {"role": "system", "content": "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."},
    {"role": "user", "content": prompt},
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True,
)
model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=512,
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]



print(response)

Your session crashed after using all available RAM.



colab t4

**Comment by tsengalb99** [comment]
If you want to chat with the model, you should use the generation script here https://github.com/Cornell-RelaxML/qtip?tab=readme-ov-file#fast-inference. If you want to load the model, you need to use the model_from_hf_path function in lib/utils/unsafe_import. Our codebase uses a modified version of the huggingface implementation of llama, where linear layers are replaced with QTIP QuantizedLinear layers.

**Comment by kim90000** [comment]
https://github.com/kim90000/xqtip/blob/main/Untitled61%20(1).ipynb
