### ISSUE TITLE
colab t4

### ISSUE THREAD

**Issue by werruww** [Cornell-RelaxML/qtip#17]
!python /content/qtip/qtip-kernels/fast-hadamard-transform/benchmarks/benchmark_fast_hadamard_transform.py --hf_path relaxml/Llama-2-7b-E8P-2Bit

Traceback (most recent call last):
  File "/content/qtip/qtip-kernels/fast-hadamard-transform/benchmarks/benchmark_fast_hadamard_transform.py", line 3, in <module>
    from flash_attn.utils.benchmark import benchmark_forward, pytorch_profiler
ModuleNotFoundError: No module named 'flash_attn'

**Comment by werruww** [comment]
flash_attn not run in colab t4

**Comment by tsengalb99** [comment]
Please open a ticket in the flash attention repo: https://github.com/Dao-AILab/flash-attention.
