### ISSUE TITLE
colab t4

### ISSUE THREAD

**Issue by werruww** [Cornell-RelaxML/qtip#18]
not run never

import torch
import transformers

model_id = "relaxml/Llama-2-7b-chat-QTIP-2Bit"

pipeline = transformers.pipeline(
    "text-generation",
    model=model_id,
)

prompet="""
3+4 = ?
"""
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompet},
            ]
outputs = pipeline(
    messages,
    max_new_tokens=512,
    do_sample=True,
    top_p=0.95,
    top_k=40,
    temperature=0.8
)
text=outputs[0]["generated_text"][-1]
print(text['content'])

crash ram in colab t4

**Comment by tsengalb99** [comment]
Our models are not designed to run with “out of the box” HF transformers. You should read the instructions in our README on how to run the models with our codebase.

From: werruww ***@***.***>
Reply-To: Cornell-RelaxML/qtip ***@***.***>
Date: Wednesday, December 11, 2024 at 1:48 PM
To: Cornell-RelaxML/qtip ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cornell-RelaxML/qtip] colab t4 (Issue #18)


not run never

import torch
import transformers

model_id = "relaxml/Llama-2-7b-chat-QTIP-2Bit"

pipeline = transformers.pipeline(
"text-generation",
model=model_id,
)

prompet="""
3+4 = ?
"""
messages = [
{"role": "system", "content": "You are a helpful assistant."},
{"role": "user", "content": prompet},
]
outputs = pipeline(
messages,
max_new_tokens=512,
do_sample=True,
top_p=0.95,
top_k=40,
temperature=0.8
)
text=outputs[0]["generated_text"][-1]
print(text['content'])

crash ram in colab t4
