### ISSUE TITLE
Hessian

### ISSUE THREAD

**Issue by laomao0** [Cornell-RelaxML/qtip#4]
Hi, How to prepare Hessian data to quant a model, e.g. LLama2-7b?

HESS=YOUR/HESSIAN/PATH/HERE

python -m quantize_llama.quantize_finetune_llama \
       --save_path $CKPT/2_7b_2bit \
       --codebook bitshift \
       --base_model meta-llama/Llama-2-7b-hf \
       --in_hess_path $HESS/hessians/llama2_7b_6144/ \
       --scale_override 0.9 \
       --ft_epochs 5 \
       --td_x 16 \
       --td_y 16 \
       --L 16 \
       --K 2 \
       --V 2 \
       --decode_mode quantlut_sym \
       --tlut_bits 9 \
       >> $LOG/2_7b_2bit 2>&1

**Comment by tsengalb99** [comment]
They're the same Hessians as QuIP# so you can use those or generate your own with the script in quantize_llama.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: laomao0 ***@***.***>
Sent: Tuesday, September 10, 2024 7:54:34 PM
To: Cornell-RelaxML/qtip ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cornell-RelaxML/qtip] Hessian (Issue #4)


Hi, How to prepare Hessian data to quant a model, e.g. LLama2-7b?

HESS=YOUR/HESSIAN/PATH/HERE

python -m quantize_llama.quantize_finetune_llama
--save_path $CKPT/2_7b_2bit
--codebook bitshift
--base_model meta-llama/Llama-2-7b-hf
--in_hess_path $HESS/hessians/llama2_7b_6144/
--scale_override 0.9
--ft_epochs 5
--td_x 16
--td_y 16
--L 16
--K 2
--V 2
--decode_mode quantlut_sym
--tlut_bits 9

**Comment by laomao0** [comment]
Thanks.
