### ISSUE TITLE
LRr, _ = utils.block_LDL(HRr, args.td_y)     TypeError: cannot unpack non-iterable NoneType object 

### ISSUE THREAD

**Issue by DmitryRedko** [Cornell-RelaxML/qtip#8]
The error occurs on both qtip and quip_sharp. When trying to quantize the model, layers 2 (1 if indexed from 0) and 31 (30 if indexed from 0) produce the same error, specifically:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/QTIP/qtip/quantize_llama/quantize_finetune_llama.py", line 76, in quantize_llama_decoder
    finetune.quantize_finetune_decoder_layer(layer, quant_order, idx, cb, args,
  File "/home/QTIP/qtip/lib/algo/finetune.py", line 118, in quantize_finetune_decoder_layer
    LRr, _ = utils.block_LDL(HRr, args.td_y)
TypeError: cannot unpack non-iterable NoneType object
```

As I understand it, this is related to the fact that when executing block_LDL, the Cholesky transformation returns None because the Hessian matrix is not positive definite. However, I don't understand why the matrix that is not positive definite ends up in ``finetune.py``:

```
HR = utils.regularize_H(HR, args.sigma_reg)
HRr = utils.matmul_hadUt(utils.matmul_hadUt(HR.to(device) * SU).T * SU)

Wscale = Wr.square().mean().sqrt() / (
    cb.lut.to(torch.float64).square().mean().sqrt().float() *
    args.scale_override)
Wr /= Wscale
LRr, _ = utils.block_LDL(HRr, args.td_y)
```

We applied regularization based on these considerations, so why does a matrix that is not positive definite still get passed?

At the output for layer 1, I get ``1_gate.pt``, ``1_k.pt``, ``1_o.pt``, ``1_q.pt``, ``1_up.pt``, and ``1_v.pt``, so the files ``1_down.pt`` and ``1_layernorm.pt`` are missing. For layer 30 the same.

BTW: I tried both downloading the Hessians and generating them myself.

**Comment by DmitryRedko** [comment]
At the output for layers 1 and 30, I get ``1_gate.pt``, ``1_k.pt``, ``1_o.pt``, ``1_q.pt``, ``1_up.pt``, and ``1_v.pt``, so the files ``1_down.pt`` and ``1_layernorm.pt`` are missing.

**Comment by tsengalb99** [comment]
Which base model is this?

**Comment by DmitryRedko** [comment]
LlaMa2-7b

**Comment by tsengalb99** [comment]
I'm not getting this issue with the Llama 2 7B Hessians we uploaded. What precision are you running the Cholesky in? And what regularization coefficient are you using? Can you try to isolate the exact layer the regularized Hessian is not PD? It seems like 1_down may be an issue based on what you posted.

**Comment by tsengalb99** [comment]
https://huggingface.co/relaxml/Hessians-Llama-2-7b-6144 btw these are the Hessians we used.
